# Data Exploration

### Libraries

In [1]:
import numpy as np
from numpy.core.defchararray import add
import pandas as pd
import xlrd
import os
import plotly
import plotly.express as px

In [2]:
# New Libraries
from functools import reduce



In [ ]:
# # install new library
# !pip install plotly
#!pip install matplotlib
#!pip install seaborn
#!pip install statsmodels

### Load the pickles into data frames

In [3]:
df_hd = pd.read_pickle('houseAll.pkl')
df_pop = pd.read_pickle('metroPop.pkl')
df_hc = pd.read_pickle('metroHouse.pkl')
df_year_base = pd.read_pickle('yearTotals.pkl')
df_jobTypes = pd.read_pickle('jobTypes.pkl')
df_jobSalery = pd.read_pickle('jobSalery.pkl')
parcelNum = 'R2024320455'

## Stuff

In [4]:
df_hd.head(5)
#df_hd['GROUP'].nunique()
#df_hd.dtypes

PARCEL  Year  ACREAGE           GROUP TOWNSHIP RANGE SECTION YR BUILT  \
0  R0017650020  2000    0.246  AARON PARK SUB       3N    1E       1     1998   
1  R0017650030  2000    0.165  AARON PARK SUB       3N    1E       1     1999   
2  R0017650040  2000    0.144  AARON PARK SUB       3N    1E       1     1999   
3  R0017650050  2000    0.211  AARON PARK SUB       3N    1E       1     1998   
4  R0027000008  2000    0.270        ABBS SUB       3N    2E      21     1937   

  REMODEL YR DWELLINGS  ... GARAGE 1 SQ FT GARAGE 1 TYPE GARAGE 2 SQ FT  \
0          0       SFD  ...            476      DETACHED            280   
1          0       SFD  ...            280      DETACHED              0   
2          0       SFD  ...            280      DETACHED              0   
3          0       SFD  ...              0           NaN              0   
4       1992       SFD  ...            240      DETACHED            940   

   GARAGE 2 TYPE  POOL SQ FT       TAV  Sale Price  Sale Date  \
0       DETACHED           0  158000.0         NaN        NaT   
1            NaN           0  165800.0         NaN        NaT   
2            NaN           0  165800.0         NaN        NaT   
3            NaN           0  155000.0         NaN        NaT   
4       DETACHED           0  129100.0         NaN        NaT   

          Neighborhood         Area  
0  NORTH CENTRAL BENCH      W BOISE  
1  NORTH CENTRAL BENCH      W BOISE  
2  NORTH CENTRAL BENCH      W BOISE  
3  NORTH CENTRAL BENCH      W BOISE  
4  CENTRAL BOISE BENCH  BOISE BENCH  

[5 rows x 43 columns]

In [ ]:
#df_hd.dtypes
df_hd['Neighborhood'].unique()

In [27]:
# Abbreviated dataframe for all of the parcels
df_hd = pd.read_pickle('houseAll.pkl')
short_house = df_hd[['Year','Parcel','Year_Built','Age','Total_Sq_Ft','Bedroom_Count','Area','Neighborhood','TAV']]
short_house.to_pickle('short_house.pkl')
short_house.head()

Year       Parcel Year_Built  Age  Total_Sq_Ft  Bedroom_Count         Area  \
0  2000  R0017650020       1998    2         2400              4      W BOISE   
1  2000  R0017650030       1999    1         2352              4      W BOISE   
2  2000  R0017650040       1999    1         2352              4      W BOISE   
3  2000  R0017650050       1998    2         2352              4      W BOISE   
4  2000  R0027000008       1937   63         3008              1  BOISE BENCH   

          Neighborhood       TAV  
0  NORTH CENTRAL BENCH  158000.0  
1  NORTH CENTRAL BENCH  165800.0  
2  NORTH CENTRAL BENCH  165800.0  
3  NORTH CENTRAL BENCH  155000.0  
4  CENTRAL BOISE BENCH  129100.0

In [43]:
#short_house.loc[short_house['PARCEL'] == parcelNum]
short_house = pd.read_pickle('short_house.pkl')
myA = short_house[short_house['Area'] == 'BOISE BENCH']
myA.to_pickle('myA.pkl')
myN = short_house[short_house['Neighborhood'] == 'CENTRAL BOISE BENCH']
myN.to_pickle('myN.pkl')
myN.head()

Year       Parcel Year_Built  Age  Total_Sq_Ft  Bedroom_Count         Area  \
4  2000  R0027000008       1937   63         3008              1  BOISE BENCH   
5  2000  R0027000013       1937   63         1704              4  BOISE BENCH   
6  2000  R0027000018       1937   63         2330              2  BOISE BENCH   
7  2000  R0027000025       1950   50          625              2  BOISE BENCH   
8  2000  R0027000030       1950   50          676              1  BOISE BENCH   

          Neighborhood       TAV  
4  CENTRAL BOISE BENCH  129100.0  
5  CENTRAL BOISE BENCH   85200.0  
6  CENTRAL BOISE BENCH  106700.0  
7  CENTRAL BOISE BENCH   46400.0  
8  CENTRAL BOISE BENCH   59600.0

In [42]:
myA.head()

Year       Parcel Year_Built  Age  Total_Sq_Ft  Bedroom_Count         Area  \
4  2000  R0027000008       1937   63         3008              1  BOISE BENCH   
5  2000  R0027000013       1937   63         1704              4  BOISE BENCH   
6  2000  R0027000018       1937   63         2330              2  BOISE BENCH   
7  2000  R0027000025       1950   50          625              2  BOISE BENCH   
8  2000  R0027000030       1950   50          676              1  BOISE BENCH   

          Neighborhood       TAV  
4  CENTRAL BOISE BENCH  129100.0  
5  CENTRAL BOISE BENCH   85200.0  
6  CENTRAL BOISE BENCH  106700.0  
7  CENTRAL BOISE BENCH   46400.0  
8  CENTRAL BOISE BENCH   59600.0

### Searching code 

# Big merge for testing LM

In [45]:
jobTypes = pd.read_pickle('jobTypes.pkl')
jobSalery = pd.read_pickle('jobSalery.pkl')
yearTotals = pd.read_pickle('yearTotals.pkl')
myN = pd.read_pickle('myN.pkl')
myA = pd.read_pickle('myA.pkl')

dfn = [myN, jobTypes, jobSalery, yearTotals]
dfa = [myA, jobTypes, jobSalery, yearTotals]
dfN = reduce(lambda left,right: pd.merge(left,right, on = 'Year'), dfn)
dfA = reduce(lambda left,right: pd.merge(left,right, on = 'Year'), dfa)
dfN.to_pickle('NmodelDF.pkl')
dfA.to_pickle('AmodelDF.pkl')
dfM

Year       Parcel Year_Built  Age  Total_Sq_Ft  Bedroom_Count  \
0       2000  R0027000008       1937   63         3008              1   
1       2000  R0027000013       1937   63         1704              4   
2       2000  R0027000018       1937   63         2330              2   
3       2000  R0027000025       1950   50          625              2   
4       2000  R0027000030       1950   50          676              1   
5       2000  R0027000035       1941   59         1810              2   
6       2000  R0027000040       1949   51         4976              4   
7       2000  R0027000047       1948   52         1848              4   
8       2000  R0027000050       1950   50         1806              3   
9       2000  R0027000060       1946   54         1900              3   
10      2000  R0027000065       1935   65         1179              3   
11      2000  R0027000080       1938   62         1240              2   
12      2000  R0027000080       1938   62         1348              2   
13      2000  R0027000085       1950   50         1592              2   
14      2000  R0027000085       1950   50          600              1   
15      2000  R0027000105       1950   50         1846              2   
16      2000  R0027000112       1983   17         1523              3   
17      2000  R0027000120       1952   48         2600              4   
18      2000  R0027000130       1977   23         1260              3   
19      2000  R0027000135       1935   65         1123              2   
20      2000  R0027000142       1939   61         1456              2   
21      2000  R0027000147       1991    9         2380              4   
22      2000  R0027000150       1980   20         3648              3   
23      2000  R0027000155       1935   65         2360              3   
24      2000  R0027000160       1971   29         1650              3   
25      2000  R0027000166       1935   65         2576              4   
26      2000  R0027000170       1930   70          698              2   
27      2000  R0027000172       1979   21         1103              3   
28      2000  R0027000181       1928   72         1560              3   
29      2000  R0027000185       1970   30         1710              4   
...      ...          ...        ...  ...          ...            ...   
221334  2018  S1020449000       2017    1         1801              3   
221335  2018  S1020449110       1975   43         1400              3   
221336  2018  S1021141800       1971   47         1650              4   
221337  2018  S1021141810       1971   47         1650              3   
221338  2018  S1021141820       1952   66         1843              2   
221339  2018  S1021141850       1948   70          837              2   
221340  2018  S1021141866       1948   70         1544              3   
221341  2018  S1021346600       1970   48         1493              3   
221342  2018  S1021346700       1974   44         1604              3   
221343  2018  S1021417250       1955   63         1534              3   
221344  2018  S1021417250       2010    8          440              1   
221345  2018  S1021417260       1955   63         1440              3   
221346  2018  S1021417270       1955   63         1344              3   
221347  2018  S1021417280       1962   56         1632              4   
221348  2018  S1021417290       1962   56         1976              4   
221349  2018  S1021449003       1996   22         1539              3   
221350  2018  S1021449006       1996   22         1539              3   
221351  2018  S1022120675       1963   55         1728              4   
221352  2018  S1022120700       1962   56         2080              3   
221353  2018  S1022120725       1950   68         1358              2   
221354  2018  S1022120750       1944   74         1708              3   
221355  2018  S1022120801       1940   78         1174              3   
221356  2018  S1022120825       1940   78         1356            

# Testing LM

New try for Linear Regression Multiple Variables, https://www.youtube.com/watch?v=J_LnPL3Qg70

In [35]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [46]:
# Using myN to make a dataframe that is like the example in the tutorial
miniTestN = dfN[['Total_Sq_Ft','Bedroom_Count','Age','TAV']]
miniTestA = dfA[['Total_Sq_Ft','Bedroom_Count','Age','TAV']]
miniTest.head()

Total_Sq_Ft  Bedroom_Count  Age       TAV
0         3008              1   63  129100.0
1         1704              4   63   85200.0
2         2330              2   63  106700.0
3          625              2   50   46400.0
4          676              1   50   59600.0

In [47]:
regN = linear_model.LinearRegression()
regA = linear_model.LinearRegression()
# reg.fit(ind vars, dep var)
regN.fit(miniTestN[['Total_Sq_Ft','Bedroom_Count','Age']],miniTestN.TAV)
regA.fit(miniTestA[['Total_Sq_Ft','Bedroom_Count','Age']],miniTestA.TAV)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [48]:
regN.coef_

array([   100.6168817 , -20366.92677957,   -271.96607904])

In [49]:
regA.coef_

array([    91.29397198, -17435.07706942,   -111.23269607])

In [50]:
regN.intercept_

62074.57054273541

In [52]:
regA.intercept_

57008.137275928384

In [56]:
regN.predict([[1700,3,75]])

array([151625.03317004])

In [57]:
# this makes since because there are very few change variables only age goes up by 1 and the TAV goes up, needs the rest
regA.predict([[1700,3,75]])

array([151560.20622664])

In [55]:
myN.loc[myN['Parcel'] == parcelNum]

Year       Parcel Year_Built  Age  Total_Sq_Ft  Bedroom_Count  \
16712    2000  R2024320455       1945   55         1704              3   
71663    2001  R2024320455       1945   56         1704              3   
127327   2002  R2024320455       1945   57         1704              3   
183747   2003  R2024320455       1945   58         1704              3   
241243   2004  R2024320455       1945   59         1704              3   
300655   2005  R2024320455       1945   60         1704              3   
362600   2006  R2024320455       1945   61         1704              3   
425158   2007  R2024320455       1945   62         1704              3   
488445   2008  R2024320455       1945   63         1704              3   
552253   2009  R2024320455       1945   64         1704              3   
616726   2010  R2024320455       1945   65         1704              3   
681636   2011  R2024320455       1945   66         1704              3   
747048   2012  R2024320455       1945   67         1704              3   
812971   2013  R2024320455       1945   68         1704              3   
879283   2014  R2024320455       1945   69         1704              3   
946227   2015  R2024320455       1945   70         1704              3   
1014255  2016  R2024320455       1945   71         1704              3   
1083028  2017  R2024320455       1945   72         1704              3   
1152303  2018  R2024320455       1945   73         1704              3   
1222110  2019  R2024320455       1945   74         1704              3   

                Area         Neighborhood       TAV  
16712    BOISE BENCH  CENTRAL BOISE BENCH   85000.0  
71663    BOISE BENCH  CENTRAL BOISE BENCH   93500.0  
127327   BOISE BENCH  CENTRAL BOISE BENCH   99300.0  
183747   BOISE BENCH  CENTRAL BOISE BENCH   99300.0  
241243   BOISE BENCH  CENTRAL BOISE BENCH  100800.0  
300655   BOISE BENCH  CENTRAL BOISE BENCH  115600.0  
362600   BOISE BENCH  CENTRAL BOISE BENCH  140300.0  
425158   BOISE BENCH  CENTRAL BOISE BENCH  163600.0  
488445   BOISE BENCH  CENTRAL BOISE BENCH  164600.0  
552253   BOISE BENCH  CENTRAL BOISE BENCH  144700.0  
616726   BOISE BENCH  CENTRAL BOISE BENCH  117900.0  
681636   BOISE BENCH  CENTRAL BOISE BENCH  103500.0  
747048   BOISE BENCH  CENTRAL BOISE BENCH  101400.0  
812971   BOISE BENCH  CENTRAL BOISE BENCH  118400.0  
879283   BOISE BENCH  CENTRAL BOISE BENCH  138300.0  
946227   BOISE BENCH  CENTRAL BOISE BENCH  151000.0  
1014255  BOISE BENCH  CENTRAL BOISE BENCH  152600.0  
1083028  BOISE BENCH  CENTRAL BOISE BENCH  168300.0  
1152303  BOISE BENCH  CENTRAL BOISE BENCH  209100.0  
1222110  BOISE BENCH  CENTRAL BOISE BENCH  264200.0

In [ ]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [ ]:
x = pd.DataFrame(np.c)
y = ['T']

In [ ]:
dfL.describe()

In [ ]:
sns.distplot(dfL['TAV'])

In [ ]:
#myN.info()
#jobTypes.info()
#jobSalery.info()
yearTotals.info()

# Testing outliers and getting the data into graphing and analysis

In [ ]:
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import numpy as np
import warnings
import matplotlib.pyplot as plt

In [ ]:
sns.set(rc={'figure.figsize':(12, 7.5)})
sns.set_context('talk')

In [ ]:

#df_hd.loc[df_hd['GROUP'] == 'ELIZABETH PL']

#tBlock = short_house.loc[(short_house['TOWNSHIP'] == '3N')&(short_house['RANGE']=='2E')&(short_house['SECTION']==16)]

#tList = tBlock[tBlock['GROUP'].str.contains(r'GLEN)]
#tList.GROUP.unique()


In [ ]:
myN00 = myN[myN['YEAR'] == 2000]
myN00.to_pickle('myN00.pkl')
myN00.head()

In [ ]:
sns.distplot(myN00['TAV'])

$z$ - score $ = \frac{x-\mu}{\sigma}$

In [ ]:
#mean
myNmean = myN['TAV'].mean()

# standard deviation
myNsd = myN['TAV'].std()

myN00['Z-Score'] = (myN00['TAV']-myNmean)/myNsd

myN00.to_pickle('myN00.pkl')
myN00.head()
#myNmean
#myNsd

In [ ]:
myN00['Z-Score'].min()
myN00['Z-Score'].min()
#sns.distplot(myN00['Z-Score'])

# Make df for all neighborhoods over each year

In [ ]:
# make list of neighborhoods

# make list of years

In [ ]:
# make a fn to make a vector for average house $ for a neighborhood for each year





In [ ]:
# make a df where each column is one of the vectors made from the fn




In [ ]:
myN00 = pd.read_pickle('myN00.pkl')

myN00F = myN00.loc[(myN00['Z-Score'] <= 3) & (myN00['Z-Score'] >= -3) ]
#myN00 = myN00.drop(myN00[myN00['Z-Score'] <= 3].index, inplace = True)
#myN00['Z-Score'].max()
myN00F.head()

In [ ]:
myN00['Z-Score'].max()

In [ ]:
myN00.shape

In [ ]:
sns.distplot(myN00F['TAV'], color = "maroon")

## Figure out IQR
$$IQR = Q3-Q1$$
Outliers:
    $$<(Q1 - 1.5 * IQR)$$
    $$>(Q3 + 1.5 * IQR)$$

In [ ]:
myN00q1 = myN00['TAV'].quantile(0.25)
myN00q3 = myN00['TAV'].quantile(0.75)
myN00iqr = myN00q3 - myN00q1
iqrMax = myN00q3 + (1.5*myN00iqr)
iqrMin = myN00q1 - (1.5*myN00iqr)
myN00iqr

In [ ]:
myN00 = pd.read_pickle('myN00.pkl')
myN00i = myN00[(myN00['TAV']<iqrMax) & (myN00['TAV'] > iqrMin)]
myN00i['TAV'].max()

In [ ]:
print(myN00F['TAV'].max())
print(myN00q3+(1.5*myN00iqr))

In [ ]:
sns.distplot(myN00i['TAV'])
#sns.distplot(myN00F['TAV'], color = "maroon")

In [ ]:
myN00i['TAV'].hist()

In [ ]:
#df_year_base

import plotly
import plotly.express as px

fig1 = px.line(df_year_base, x='Year', y = 'TotalHouse')
fig2 = px.line(df_year_base, x='Year', y = 'TotalPop')
fig2.show()

In [ ]:
df_year_base.info()

# Graph Stuff

In [ ]:
import plotly
import plotly.express as px

fig1 = px.box(mySec, x='YEAR', y = 'TAV')
fig1.show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data =go.Scatter(
        x = mySec['YEAR'],
        y = mySec['TAV']))

fig.show()

### Look into z-scores for trimming the outliers
https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba